/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package resolucionexamen;

import javax.swing.JOptionPane;

/**
 *
 * @author CURLING
 */
public class formulario extends javax.swing.JFrame {

   ClsEncuesta encuesta = new ClsEncuesta();
   
    public formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tedad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tnombre = new javax.swing.JTextField();
        rsi = new javax.swing.JRadioButton();
        rno = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tcorreo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lnumero = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lno = new javax.swing.JLabel();
        lsi = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel1.setText("Tiene Carro?");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 180, 90, 40);

        jLabel2.setText("Edad");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 100, 90, 40);
        jPanel1.add(tedad);
        tedad.setBounds(150, 110, 80, 22);

        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 60, 90, 40);
        jPanel1.add(tnombre);
        tnombre.setBounds(150, 70, 180, 22);

        buttonGroup1.add(rsi);
        rsi.setSelected(true);
        rsi.setText("Si");
        jPanel1.add(rsi);
        rsi.setBounds(160, 190, 60, 20);

        buttonGroup1.add(rno);
        rno.setText("No");
        jPanel1.add(rno);
        rno.setBounds(260, 190, 98, 20);

        jButton1.setText("Salvar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 260, 170, 60);

        jLabel4.setText("Correo");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 140, 90, 40);
        jPanel1.add(tcorreo);
        tcorreo.setBounds(150, 150, 180, 22);

        jLabel5.setText("NUMERO ENCUESTA:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(210, 20, 170, 30);

        lnumero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lnumero.setForeground(new java.awt.Color(255, 0, 0));
        lnumero.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lnumero);
        lnumero.setBounds(390, 10, 90, 60);

        jLabel6.setText("No Tienen Carro");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(390, 220, 110, 16);

        jLabel7.setText("Tienen Carro");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(400, 110, 80, 16);

        lno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lno);
        lno.setBounds(400, 250, 60, 40);

        lsi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lsi);
        lsi.setBounds(400, 150, 60, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(100, 30, 510, 400);

        jMenu2.setText("Inicio");

        jMenuItem1.setText("Reportes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      
       this.show();
      lnumero.setText(String.valueOf(encuesta.getConsecutivo()));
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        if (!tedad.getText().equals("") && !tnombre.getText().equals("") && !tcorreo.getText().equals(""))
        {
            
            if ( (Integer.parseInt(tedad.getText())< 18) || (Integer.parseInt(tedad.getText())>50)  ) 
           {
              JOptionPane.showMessageDialog(null, "La edad no es permitida");
           } 
            else 
           {
               boolean tienecarro = false;
               if (rsi.isSelected()) {
                   tienecarro = true;
                   encuesta.setConVehiculo();
               } else if (rno.isSelected()) {
                   tienecarro = false;
                   encuesta.setSinVehiculo();
               }
           encuesta.SetSalvarDatos(tnombre.getText(), tienecarro, Integer.parseInt(tedad.getText()), tcorreo.getText());
           lnumero.setText(String.valueOf(ClsEncuesta.getConsecutivo()));
           encuesta.setConsecutivo();
           lsi.setText(String.valueOf(ClsEncuesta.getConVehiculo()));
           lno.setText(String.valueOf(ClsEncuesta.getSinVehiculo()));
          } 
                
        tnombre.setText("");
        tedad.setText("");
        tcorreo.setText("");
        rsi.setSelected(true);
        } 
        else {
        JOptionPane.showMessageDialog(null, "Los campos estan en blanco");
        
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        
    }//GEN-LAST:event_jButton1MouseEntered

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
          FrmReporte reporte = new FrmReporte();
          reporte.setSize(700, 500);
          reporte.setVisible(true);
          
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lno;
    private javax.swing.JLabel lnumero;
    private javax.swing.JLabel lsi;
    private javax.swing.JRadioButton rno;
    private javax.swing.JRadioButton rsi;
    private javax.swing.JTextField tcorreo;
    private javax.swing.JTextField tedad;
    private javax.swing.JTextField tnombre;
    // End of variables declaration//GEN-END:variables
}
