package resolucionexamen;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author CURLING
 */
public class FrmReporte extends javax.swing.JFrame {

    /**
     * Creates new form FrmReporte
     */
    public FrmReporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lcantidad = new javax.swing.JLabel();
        lconcarro = new javax.swing.JLabel();
        lsincarro = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tnombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bbuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("REPORTES");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 30, 330, 60);

        jLabel2.setText("Personas Sin Carro Propio");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 100, 170, 50);

        jLabel3.setText("Personas con Carro Propio");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 100, 170, 50);

        jLabel4.setText("Cantidad de Encuestas");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 120, 160, 16);

        lcantidad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lcantidad.setForeground(new java.awt.Color(0, 102, 255));
        lcantidad.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(lcantidad);
        lcantidad.setBounds(450, 150, 100, 60);

        lconcarro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lconcarro.setForeground(new java.awt.Color(0, 102, 255));
        lconcarro.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(lconcarro);
        lconcarro.setBounds(90, 160, 90, 50);

        lsincarro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lsincarro.setForeground(new java.awt.Color(0, 102, 255));
        lsincarro.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(lsincarro);
        lsincarro.setBounds(260, 150, 90, 60);

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 330, 110, 30);
        getContentPane().add(tnombre);
        tnombre.setBounds(200, 270, 130, 22);

        jLabel5.setText("Buscar por nombre");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(77, 260, 190, 40);

        bbuscar.setText("Buscar");
        bbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(bbuscar);
        bbuscar.setBounds(440, 270, 140, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.hide();
      
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       
       lconcarro.setText(String.valueOf(ClsEncuesta.getConVehiculo()));
       lsincarro.setText(String.valueOf(ClsEncuesta.getSinVehiculo()));
       lcantidad.setText(String.valueOf(ClsEncuesta.getConsecutivo()));
        
    }//GEN-LAST:event_formWindowActivated

    private void bbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbuscarActionPerformed
       ClsEncuesta.BuscarPornombre(tnombre.getText());
        
    }//GEN-LAST:event_bbuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmReporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lcantidad;
    private javax.swing.JLabel lconcarro;
    private javax.swing.JLabel lsincarro;
    private javax.swing.JTextField tnombre;
    // End of variables declaration//GEN-END:variables
}
